name: mdlenz
description: "A notes app built untop of MarkDown for better visuals"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  page_transition: ^2.2.1
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1 
  flutter_markdown: ^0.6.15
  path_provider: ^2.1.1
  file_picker: ^9.1.0
  url_launcher: ^6.0.0
  local_auth: ^2.3.0
  share_plus: ^10.1.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
